spring:
  config:
    activate:
      on-profile: test

# Applikationsspezifische Einstellungen
app:
  server:
    port: ${TEST_SERVER_PORT}
  mongo:
    database: ${TEST_MONGODB_DATABASE}
  http2:
   enabled: false
  ssl:
   enabled: false